name: Deploy to Firebase Hosting using Workload Identity Federation

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/348958277147/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "firebase-deploy@projectsignupapi.iam.gserviceaccount.com"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --project projectsignupapi --only hosting
